import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";



const luxurious = localFont({
  src: "./fonts/LuxuriousRoman-Regular.ttf",
  variable: "--font-luxurious",
});

const pinyon = localFont({
  src: "./fonts/PinyonScript-Regular.ttf",
  variable: "--font-pinyon",
})

const voyage = localFont({
  src: "./fonts/Voyage-Regular.ttf",
  variable: "--font-voyager",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${luxurious.variable} ${pinyon.variable} ${voyage.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* <Navbar /> */}
        {children}
        </body>
    </html>
  );
}
